# Generated by Django 5.2.17 on 2026-08-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.CharField(blank=True, max_length=20, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('frames_analyzed', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
